name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the appropriate runner for your server environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh -ldima 167.71.66.184 'cd /try2 && git pull'
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash
